// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopServices.Api.Carrinho.Data;

#nullable disable

namespace ShopServices.Api.Carrinho.Migrations
{
    [DbContext(typeof(CarrinhoContext))]
    [Migration("20220331103750_TabelaMySqlInicial")]
    partial class TabelaMySqlInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShopServices.Api.Carrinho.Models.CarrinhoCompra", b =>
                {
                    b.Property<int>("CarrinhoCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.HasKey("CarrinhoCompraId");

                    b.ToTable("Carrinho", (string)null);
                });

            modelBuilder.Entity("ShopServices.Api.Carrinho.Models.CarrinhoCompraItem", b =>
                {
                    b.Property<int>("CarrinhoItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CarrinhoCompraId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ProdutoSelecionado")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.HasKey("CarrinhoItemId");

                    b.HasIndex("CarrinhoCompraId");

                    b.ToTable("CarrinhoItem", (string)null);
                });

            modelBuilder.Entity("ShopServices.Api.Carrinho.Models.CarrinhoCompraItem", b =>
                {
                    b.HasOne("ShopServices.Api.Carrinho.Models.CarrinhoCompra", "Carrinho")
                        .WithMany("ListaDetalhe")
                        .HasForeignKey("CarrinhoCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");
                });

            modelBuilder.Entity("ShopServices.Api.Carrinho.Models.CarrinhoCompra", b =>
                {
                    b.Navigation("ListaDetalhe");
                });
#pragma warning restore 612, 618
        }
    }
}
