// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopServices.Api.Livro.Data;

#nullable disable

namespace ShopServices.Api.Livro.Migrations
{
    [DbContext(typeof(LivroContext))]
    [Migration("20220329100916_ShopLivroInicialSqlServer")]
    partial class ShopLivroInicialSqlServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShopServices.Api.Livro.Models.Biblioteca", b =>
                {
                    b.Property<Guid?>("BibliotecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutorLivro")
                        .HasMaxLength(36)
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("BibliotecaId");

                    b.ToTable("Bibliotecas", (string)null);

                    b.HasData(
                        new
                        {
                            BibliotecaId = new Guid("189dd0ad-606a-472c-b1f8-3e764a21d297"),
                            AutorLivro = new Guid("49f9e020-808d-4fd0-8ce8-2bd76a7ba199"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1640),
                            Titulo = "Titulo 01"
                        },
                        new
                        {
                            BibliotecaId = new Guid("17877ba0-6e53-4a66-ba94-8c86152b7d45"),
                            AutorLivro = new Guid("c7606156-c165-4da5-9e7d-28af654bb97d"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1644),
                            Titulo = "Titulo 02"
                        },
                        new
                        {
                            BibliotecaId = new Guid("6c02b533-1f7c-4e47-bcc8-a24bb5412c26"),
                            AutorLivro = new Guid("368e956e-f665-4291-9a1a-53fc4cb4338a"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1647),
                            Titulo = "Titulo 03"
                        },
                        new
                        {
                            BibliotecaId = new Guid("bde285f7-17e0-4c77-a7ac-9e44839c6027"),
                            AutorLivro = new Guid("8bf309ec-b958-4bcd-99f4-c7dd110c376d"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1649),
                            Titulo = "Titulo 04"
                        },
                        new
                        {
                            BibliotecaId = new Guid("12324117-b504-4bfa-a2eb-4e584629f0d2"),
                            AutorLivro = new Guid("de2eb41d-c9fd-4a5f-bbd9-57a8759d5cdb"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1650),
                            Titulo = "Titulo 05"
                        },
                        new
                        {
                            BibliotecaId = new Guid("6ebf97db-7b1c-4398-8fe4-4b16217db901"),
                            AutorLivro = new Guid("25142ffd-7ea7-4de0-afce-3ec447536c27"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1652),
                            Titulo = "Titulo 06"
                        },
                        new
                        {
                            BibliotecaId = new Guid("60f033ca-8718-4a60-98d2-45c2e4d68b56"),
                            AutorLivro = new Guid("cd6087c4-48c8-4c25-a704-41af2e0271b3"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1654),
                            Titulo = "Titulo 07"
                        },
                        new
                        {
                            BibliotecaId = new Guid("db84bc00-0cb1-4bec-baed-17dcfec26f03"),
                            AutorLivro = new Guid("90bd9ee0-da94-48ef-8377-a3d9122868d3"),
                            DataPublicacao = new DateTime(2022, 3, 29, 10, 9, 16, 216, DateTimeKind.Utc).AddTicks(1663),
                            Titulo = "Titulo 08"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
